---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
  namespace: trulabelsas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
        - name: control-center
          image: confluentinc/cp-enterprise-control-center:7.5.0
          ports:
            - containerPort: 9021
          env:
            - name: CONFLUENT_METRICS_TOPIC_REPLICATION
              value: "1"
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: kafka:29092
            - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: "1"
            - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
              value: schema-registry:8082
            - name: PORT
              value: "9021"
          readinessProbe:
            tcpSocket:
              port: 9021
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: control-center
  namespace: trulabelsas
spec:
  ports:
    - port: 9021
  selector:
    app: control-center
