apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - zookeeper.yaml
  - kafka.yaml
  - schema-registry.yaml
  - init-topics.yaml
  - mongo.yaml
  - init-mongo.yaml  
  - control-center.yaml
