apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.0
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: saas
spec:
  ports:
    # - port: 2181
    - protocol: TCP
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper

